### ISSUE TITLE
Inconsistent chapter naming from reader versus R markdown

### ISSUE THREAD

**Issue by 82817** [mschermann/data_viz_reader#763] opened 2019-04-05 00:46 UTC
Inside the reader, Preface is named under chapter 1; while in the files under Code folder, Introduction seems to be the first chapter due to its naming convention. The actual preface under Code folder is named index.rmd

I'm not sure if there is a purpose for naming it this way, but it'll be more clear if the naming for the code and the reader can align.

**Comment by strivedi2** [comment] 2019-04-05 02:41
I noticed the same thing and it took me a couple of mins to locate the index.rmd file in the code. I think this would be a helpful change and will streamline the naming convention across the code and the reader.

**Comment by KlippL** [comment] 2019-04-05 03:42
I completely agree.  I was confused by this when I was looking in the code to make an issue after finding an error in the reader.

**Comment by bharatimalik** [comment] 2019-04-07 02:39
Definitely. It took me also a while to figure this out.

**Comment by AjayDeshmukh14** [comment] 2019-04-07 19:12
I agree with you that the naming should be consistent through the .rmd files and the reader, also the Preface must not be Chapter 1.

**Comment by 82817** [comment] 2019-05-12 03:39
I tried to edit the file name of each chapter to align with the reader but there seems to be a lot of conflicts that cannot be dissolved. I suspect that when all the chapters are knitted to the book, it references the file names somewhere and I have to change that too. 

I'll have to understand how the book was knitted in order to change this - will come back to this issue

**Comment by mschermann** [comment] 2019-05-13 15:16
@82817 let's talk to resolve your issue

**Comment by mschermann** [comment] 2019-05-16 18:47
@82817 Check this out: https://bookdown.org/yihui/bookdown/usage.html

Furthermore, I still do not quite get what the problem is or what you are trying to solve.

**Comment by 82817** [comment] 2019-05-18 01:18
@mschermann My issue is that the number of the chapter from the reader and the number from local file does not match. For example, it reads 3 Fundamental from the reader and it reads 02-Fundamentals. It creates some confusion when we try to create issues.

If you don't think this is a problem, I can go ahead and leave it. Let me know what you think!

**Comment by mschermann** [comment] 2019-05-18 02:29
The numbering is automatically generated by the bookdown package. You can read the document to see how to avoid numbering of the preface (because preface also gets a number, the numbering of the other files is off). Do not spend too much time on it. It is not critical.

**Comment by mschermann** [comment] 2019-05-20 15:12
@82817 Can we close this?

**Closed** 2019-05-20 17:12 UTC
Labels: enhancement
