### ISSUE TITLE
Content Proposal to Enhance Chapter 7: Conclusion (Includes all subsections)

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#1099] opened 2019-04-27 03:07 UTC
This is an issue to track and enhance all the subsections in chapter 7 to be more meaningful.
Our team of 4 authors will present issues (one issue per section or subsection) and a proposal to fix these 4 issues.
For section 7.1 - Future of Data Visualization - It talks about Pre-internet sociogram, Internet age sociogram and network theory.  I found following issues with section 7.1 and scope to enhance.
1)Narration can be enhanced to be short and concise.
2)It will be good to talk about Artificial Intelligence era visualization and importance of visualization in Big data world as well. 
3)This section does not talk about tools of the future data visualization. I would like to add contents to give overview about tools of the future data visualization.
Issue-1: Author/Fix By : srivasud

**Comment by Qing0608** [comment] 2019-04-27 10:02
For 7.2 section, the issue is the structure:
7.2.1 Laying the groundwork for data visualization
7.2.2 How Is It Being Used?
(content to add in this section: Improve collaboration among work teams; Establish Clear Correlation Between Business Operations And Activities etc.)
7.2.3 Helpful tips for a good visualization
(put the first part here)

**Comment by Marvin510** [comment] 2019-04-27 19:09
Section 7.3 needs additional resources. It only has Tableau links.
It needs links from other platforms such as Python, R and general links to resources for aspiring data visualizers.
 R and Pyhton have visualization packages that could be addressed and explore in this chapter.

**Comment by Kushall-Dayal** [comment] 2019-04-28 02:00
Adding to section 7.3 one other important tool that can be discussed is **D3.js** (Data Driven Documents .JavaScript):

-D3.js is a javascript library used for interactive data exploration on web pages.
-It is one of the best data exploration library available and can be seemlessly integrated in HTML and CSS code.
-It also has a huge community for support just like R and Python.

This addition would give a good mix for data visualisations tools to start from.

**Comment by rlwy** [comment] 2019-05-09 19:18
This issue has been resolved in PR #1147.

**Closed by rlwy** 2019-05-09 19:18 UTC
Labels: enhancement
